version: 2.1

parameters:
  run_release:
    type: boolean
    default: false

jobs:
  analyze:
    docker:
      - image: 'cimg/openjdk:21.0.9'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
  release:
    docker:
      - image: maven:3.9.11-eclipse-temurin-21
    steps:
      - checkout
      - run:
          name: Install GPG
          command: |
            apt-get update && apt-get install -y gnupg2 curl
      - run:
          name: Import GPG key
          command: |
            mkdir -p ~/.gnupg
            chmod 700 ~/.gnupg
      
            echo "$GPG_PRIVATE_KEY" | gpg --batch --import
            echo "$GPG_PUBLIC_KEY"  | gpg --batch --import
      
            echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
            gpgconf --reload gpg-agent
      - run:
          name: List GPG keys
          command: |
            gpg --list-keys
      - run:
          name: Setup Maven settings
          command: |
            mkdir -p ~/.m2
            cat > ~/.m2/settings.xml \<<EOL
            <settings>
              <servers>
                <server>
                  <id>central</id>
                  <username>${CENTRAL_USERNAME}</username>
                  <password>${CENTRAL_TOKEN}</password>
                </server>
              </servers>
            </settings>
            EOL
      - run:
          name: Release
          command: |
            mvn deploy -DskipTests -Proot-release
          environment:
            GPG_TTY: /dev/tty
            MAVEN_GPG_PASSPHRASE: ${GPG_PASSPHRASE}
          when: << pipeline.parameters.run_release >>
      - run:
          name: Release All
          command: |
            mvn deploy -DskipTests -Prelease
          environment:
            GPG_TTY: /dev/tty
            MAVEN_GPG_PASSPHRASE: ${GPG_PASSPHRASE}
          when: << pipeline.parameters.run_release >>

executors:
  machine_executor_amd64:
    machine:
      image: ubuntu-2204:current
    environment:
      architecture: "amd64"
      platform: "linux/amd64"

orbs:
  maven: circleci/maven@2.1.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: machine_executor_amd64
          verify_dependencies: false
      - analyze:
          context: SonarCloud
      - release:
          requires:
            - analyze
            - maven/test
          filters:
            branches:
              only: master
          context: Central